default_platform(:android)

platform :android do

  desc "Build Release APK"
  lane :build_apk do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end

  desc "Build Release AAB"
  lane :build_aab do
    gradle(
      task: "bundle",
      build_type: "Release"
    )
  end

end